// Extracts the VSOP87D series from AstrolabeCore's Swift table into JSON.
//
// The Swift table is the authority, not the IMCCE files: it is what ships,
// what the published precision figures were measured against, and what the
// parser that built it already checked term-by-term. Re-deriving from source
// data would be a second table to keep in step — the exact failure the print
// master tokens and the price list have each demonstrated this month.
//
//   node chart/tools/extract-vsop87.mjs <VSOP87.swift> <out.json>

import { readFileSync, writeFileSync } from "node:fs";

const [, , src, out] = process.argv;
if (!src || !out) {
  console.error("usage: extract-vsop87.mjs <VSOP87.swift> <out.json>");
  process.exit(2);
}
const text = readFileSync(src, "utf8");

// static let mercuryL = Series(coefficients: [ ... ], bounds: [ ... ])
const re =
  /static let (\w+)\s*=\s*Series\(\s*coefficients:\s*\[([\s\S]*?)\]\s*,\s*bounds:\s*\[([\s\S]*?)\]\s*\)/g;

const numbers = (blob) =>
  blob
    .replace(/\/\/[^\n]*/g, "")       // line comments sit between terms
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((s) => {
      const v = Number(s);
      if (!Number.isFinite(v)) throw new Error(`not a number: ${JSON.stringify(s)}`);
      return v;
    });

const series = {};
let match;
while ((match = re.exec(text)) !== null) {
  const [, name, coeffBlob, boundsBlob] = match;
  const coefficients = numbers(coeffBlob);
  const bounds = numbers(boundsBlob);

  if (coefficients.length % 3 !== 0) {
    throw new Error(`${name}: ${coefficients.length} coefficients is not a whole number of (A, B, C) triples`);
  }
  const terms = coefficients.length / 3;
  if (bounds[0] !== 0) throw new Error(`${name}: bounds must start at 0, got ${bounds[0]}`);
  if (bounds[bounds.length - 1] !== terms) {
    throw new Error(`${name}: bounds end at ${bounds[bounds.length - 1]}, table holds ${terms} terms`);
  }
  for (let i = 1; i < bounds.length; i++) {
    if (bounds[i] < bounds[i - 1]) throw new Error(`${name}: bounds go backwards at ${i}`);
  }
  series[name] = { coefficients, bounds };
}

const names = Object.keys(series);
if (names.length === 0) throw new Error("no Series found — has the Swift table's shape changed?");

const totalTerms = names.reduce((n, k) => n + series[k].coefficients.length / 3, 0);
writeFileSync(
  out,
  "// Generated by chart/tools/extract-vsop87.mjs from AstrolabeCore. Do not edit.\n" +
    "export const SERIES = " + JSON.stringify(series) + ";\n",
);
console.error(`${names.length} series, ${totalTerms} terms → ${out}`);
